config/routes.rb
Rails.application.routes.draw do
  root :to => 'layouts#index'

  resources :posts do
    resources :comments
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/pictures/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :posts
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  validates :username, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def send_welcome_message
    UserMailer.signup_confirmation(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def authorize
   if !current_user
     flash[:alert] = "You aren't authorized to visit that page."
     redirect_to '/'
   end
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize, only: [:new]

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
  @post = Post.find(params[:post_id])
  @comment = @post.comments.new(comment_params)
  if @comment.save
    flash[:notice] = "Thanks, your comment is has been added to the list!"
    redirect_to post_path(@post.id)
  else
    render :new
  end
end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update!(comment_params)
      flash[:notice] = "Your post was updated!"
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post_id = @comment.post_id
    @comment.destroy
    redirect_to post_path(@post_id)
  end


  private
  def comment_params
    params.require(:comment).permit(:comment_body)
  end

end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize, only: [:new]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(session[:user_id])
    @post = @user.posts.new(post_params)
    if @post.save
      flash[:notice] = "Thanks, your post is has been added to the list!"
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def update
    @post = Post.find(params[:id])
    if @post.update!(post_params)
      flash[:notice] = "Good job! Your post was updated!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  private
  def post_params
    params.require(:post).permit(:image, :title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand"><%= link_to "Imgur||Clone", root_path %></div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "View Posts", posts_path %></li>
        <li><%= link_to "Add Post", new_post_path %></li>
        <% if current_user %>
         <li><%= link_to "Sign out", '/signout' %></li>
         <li><%=link_to "Hi, #{current_user.username}", '/' %></li>
       <% else %>
         <li><%= link_to "Sign up", 'signup' %></li>
         <li><%= link_to "Sign in", '/signin' %></li>
       <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImgurClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for [@post], url: posts_path, html: { multipart: true } do |f| %>
  <%= f.file_field :image, as: :file %>
  <br>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <hr>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div class="table">
  <div class="row header">
    <h1>Edit <%= @post.title %></h1>
  </div>
  <div class="row">
    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<h2>Posts</h2>

<% if @posts.any? %>
      <% @posts.each do |post| %>
      <h3><%= link_to post.title, post_path(post)  %></h3>
      <div class="col-md-6" id="images">
      <div class="row">
      <%= image_tag post.image.url%>
    </div>
  </div>
      <% end %>
  <% else %>
  <p>There are no posts yet!</p>
  <% end %>

app/views/posts/new.html.erb
<h2>Add a new post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="table">
  <div class="row header">
    <h1>hello</h1>
    <%= image_tag @post.image.url %>
    <h2><%= @post.title %></h2>
    <h4><%= @post.description %></h4>
  </div>

  <hr>
  <div class="row">
    <h2>Comments:</h2>
    <% if @post.comments.any? %>
    <% @comments.each do |comment| %>
    <div>
      <h3><%= comment.body %></h3>
      <p><%= link_to "Edit", edit_post_comment_path(@post, comment) %> | <%= link_to "Delete", post_comment_path(@post, comment), :data => {
                                                  :confirm => "Are you sure?",
                                                  :method => "delete"} %></p>
    </div>
    <% end %>
  <% else %>
    <p>There are no comments yet!</p>
    <% end %>
    <p><%= link_to "Add a response", new_post_comment_path(@post) %></p>
  </div>
  <hr>
  <div class="row">
    <p><%= link_to "Edit post", edit_post_path(@post) %> |
    <%= link_to "Delete post", post_path, :data => {
                                                :confirm => "Are you sure?",
                                                :method => "delete"} %></p>
  </div>
</div>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "User Name" %>
  <%= f.text_field :username %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>